GS-284: Merge users date displays for once only courses
gchlol/moodle-tool_mergeusers pull request #7
Opened 2024-10-13 15:52 UTC by ducthanh-nguyen

## Description:

## Checklist before requesting a review:

- [x] I have performed a self review of my code.
- [x] My code follows the [Moodle Coding Style](https://moodledev.io/general/development/policies/codingstyle).
- [ ] Version numbers have been updated.
- [x] Code has been commented, particularly in hard-to-understand areas.
- [ ] Required changes have been made to the documentation (excluding epic sub-issues).
- [ ] Any new test cases have been created and existing test cases updated (excluding epic sub-issues).

2024-10-14 05:50 UTC, NickLambellGCH commented
@ducthanh-nguyen it looks like you're missing a description on this one. There's also a few non-checked tasks.
It's actually good that you didn't bump the version number since we avoid doing that for forked plugins, but you can remove the line so that it isn't counted as not done.

2025-02-26 06:25 UTC, NickLambellGCH requested changes
Thanks for the changes @ducthanh-nguyen, I've given my initial review pass comments (sorry it took so long) 😄 

As a general case that I noticed while reading through the logic. It feels like at some point we may need to delete the 'course_completions' record for `$toid` otherwise when `transfer_completion()` moves records we'd run into a unique key integrity constraint.
I haven't tested it yet, but it just seemed like something that might be an issue.

2025-02-26 06:25 UTC, NickLambellGCH commented on lang/en/tool_mergeusers.php
> +$string['mergeusers_completion_skipped'] = 'Course completion for course {$a->courseid} already exists for user {$a->toid}. Skipping merge.';
This string appears to be unused

2025-02-26 06:25 UTC, NickLambellGCH commented on lang/en/tool_mergeusers.php
> +$string['coursecompletionaction_desc'] = 'Description of the course completion action.';
These seem to be unused as well

2025-02-26 06:25 UTC, NickLambellGCH commented on lib/table/coursecompletiontablemerger.php
> +     * @param array $errorMessages list of error messages.
These can be updated to more specifically define the params as string arrays with `string[]` instead of just `array`.
I try to avoid the generic `array` where possible with the exception being cases like `$data` here where it is actually just an array of arbitrary data rather than a list of items.
I won't comment on all the occurrences, but I'll get you to make the changes to the whole file.

2025-02-26 06:25 UTC, NickLambellGCH commented on lib/table/coursecompletiontablemerger.php
> +
Looks like this is missing the "This file is part of Moodle ..." license blurb at the top. Not critical but good for consistency 😄

2025-02-26 06:25 UTC, NickLambellGCH commented on lib/table/coursecompletiontablemerger.php
> +    public function merge($data, &$actionLog, &$errorMessages) {
Can I get you to add param and return types here and to the other functions in this class?

2025-02-26 06:25 UTC, NickLambellGCH commented on lib/table/coursecompletiontablemerger.php
> +     * @param object $existingCompletion Course completion record for the new user.
These should be `stdClass` rather than `object`

2025-02-26 06:25 UTC, NickLambellGCH commented on lib/table/coursecompletiontablemerger.php
> +        }
I think this logic might need a bit of a rework. My main indicator for this is that 4 of the possible code paths make exactly the same `move_to_recompletion(...)` call.

I was thinking through it a bit and came to this pseudo code logic flow which might work. Let me know if you have any thoughts on it 😄 
```
if both no timestamp {
	return
}

if existing completion no timestamp {
	delete existing completion?
	transfer new completion
	
	return
}

if new completion < existing completion {
	send new completion to archive
	
	return
}

archive existing completion
transfer new completion
```

2025-02-26 06:25 UTC, NickLambellGCH commented on lib/table/coursecompletiontablemerger.php
> +        $completion->userid = $toid;
You should always be careful modifying parameters. As a general rule I always avoid it since PHP has somewhat interesting handling sometimes.
In this case, since the param is a stdClass, any modifications to its properties actually flow back into the variable that was used to call the function.

If I want to modify an input param stdClass , I'll always clone it and then use the clone. e.g.
```php
$updatecompletion = clone $completion;
$updatecompletion->userid = $doid;
```
The only catch to note is that this is a shallow clone, so if a property of the object is another object, that object will still be by reference. There are ways to do a deep recursive clone if we ever run into that case but luckily most of our objects are single level 😄

2025-02-26 06:25 UTC, NickLambellGCH commented on lib/table/coursecompletiontablemerger.php
> +        $recompletionData = new stdClass();
`$recompletionData` should be `$recompletiondata` with no caps

2025-02-26 06:25 UTC, NickLambellGCH commented on lib/table/coursecompletiontablemerger.php
> +            ]);
New line after the last line in a block where it has content (`catch` in this case) directly after is good

2025-02-26 06:25 UTC, NickLambellGCH commented on lib/table/coursecompletiontablemerger.php
> +        ]);
The length / splitting of this call is a bit awkward as can happen with `get_string`. Usually, I'll just put each param on its own line and since the data array only has a single entry, it can be collapsed into a single line.

2025-02-26 06:25 UTC, NickLambellGCH commented on lib/table/coursecompletiontablemerger.php
> +                    'toid' => $toid
The last entry in multi-line arrays should have a trailing comma.
There's a couple of these in other functions too 😄

2025-02-26 06:25 UTC, NickLambellGCH commented on lib/table/coursecompletiontablemerger.php
> +            if (!$existingCompletion) {
Logic where you have something like `if($x)` immediately followed by `if(!$x)` usually indicates that the logic could be improved a bit.
In the least optimal cases you can at least change it to an `if ... else` but if you're inside a control structure like a function or loop like this case, you can do it even better.
In this case you should just `continue` after your logic in `if ($existingCompletion)`. Then completely remove the `if (!$existingCompletion)` and place the logic directly in the loop since it will never reach that point if `$existingCompletion` is truthy.

2025-03-10 23:28 UTC, ducthanh-nguyen commented on lang/en/tool_mergeusers.php
> +$string['coursecompletionaction_desc'] = 'Description of the course completion action.';
I missed pushing the settings file

2025-03-11 00:34 UTC, ducthanh-nguyen commented on lib/table/coursecompletiontablemerger.php
> +        }
For existing completion no timestamp, although a completion 'timecompleted' is null, 'timestarted' is different which might be used for reference. Just wondering if we should keep this and an older 'timestarted' might be more valuable (in most cases, existing completion).

2025-03-11 01:02 UTC, NickLambellGCH commented on lib/table/coursecompletiontablemerger.php
> +        }
I just checked how recompletion handles non-completed courses and there's a bit of a mix. The scheduled task periodic reset skips users with non-completion but manual resets don't check at all and will archive non-completion.
Like you say though, since we're merging users, it's probably good to have the archive as reference. Since that's the case I think it actually simplifies the logic as we can just remove the 'if existing completion no timestamp' part and let it flow through 😄

2025-04-08 04:23 UTC, NickLambellGCH requested changes

2025-04-08 04:23 UTC, NickLambellGCH commented on lib/table/coursecompletiontablemerger.php
> +    private mixed $action;
It looks like this property is never used.
The `mixed` type isn't a real type either but rather just one that can be used in PHPDoc. In cases like this where you are storing the result of a `mixed` return type function you can either leave off the prop type or where you should have a known return type like with `get_config()`, you can cast the return value.

2025-04-08 04:23 UTC, NickLambellGCH commented on settings.php
> +        1));
Since the property this setting is read into in `CourseCompletionTableMerger` isn't used, the setting can probably be removed.

2025-04-08 04:23 UTC, NickLambellGCH commented on lib/table/coursecompletiontablemerger.php
> +        $oldCompletions = $DB->get_records('course_completions', ['userid' => $fromid]);
Variables should be all lower case where possible. The only ones that can't be here are the ones passed into the function since it's an override.

2025-04-08 04:23 UTC, NickLambellGCH commented on lib/table/coursecompletiontablemerger.php
> +                continue;
Should be a new line before keywords like `continue`

2025-04-08 04:23 UTC, NickLambellGCH commented on lib/table/coursecompletiontablemerger.php
> +        if (empty($completion->timecompleted) && empty($existingCompletion->timecompleted)) {
`if` statements with multiple conditions should be expanded to be multi-line

2025-04-08 04:23 UTC, NickLambellGCH commented on lib/table/coursecompletiontablemerger.php
> +            (empty($existingCompletion->timecompleted) || $completion->timecompleted > $existingCompletion->timecompleted)) {
Should be made fully multi-line as above

2025-04-08 04:23 UTC, NickLambellGCH commented on lib/table/coursecompletiontablemerger.php
> +            return;
Should be a new line before `return`

2025-04-08 04:23 UTC, NickLambellGCH commented on lib/table/coursecompletiontablemerger.php
> +        $actionLog[] = "Moving course completion (Course ID: {$completion->course}) to recompletion for user {$userid}.";
Should this be a language string?

2025-04-08 04:23 UTC, NickLambellGCH commented on lang/en/tool_mergeusers.php
> +$string['mergeusers_recompletion_error'] = 'Error moving course {$a->courseid} completion for user {$a->userid} to recompletion: {$a->error}.';
Language strings typically shouldn't need the name of the plugin, 'mergeusers_' prefix in this case, as it's already unique to the file and referenced by the plugin in any `get_string()` calls.
In most cases, they also shouldn't have underscores. The main exception being '_help' and '_desc'.

2025-04-08 04:23 UTC, NickLambellGCH commented on lib/table/coursecompletiontablemerger.php
> +
Minor one but something the inspection I'm working on integrating into the project picked up on. There shouldn't be a new line between the PHP open tag and the license blurb

2025-04-11 02:55 UTC, NickLambellGCH requested changes

2025-04-11 02:55 UTC, NickLambellGCH commented on lib/table/coursecompletiontablemerger.php
>          $this->action = get_config('tool_mergeusers', 'coursecompletionaction');
Since the 'coursecompletionaction' setting no longer exists, the entire constructor should be removed.

2025-04-11 02:55 UTC, NickLambellGCH commented on lib/table/coursecompletiontablemerger.php
> +            empty($existingCompletion->timecompleted)) {
When expanding an `if` statement to be multi-line, each condition should be on its own line separate from the opening and closing parenthesis

2025-04-11 02:55 UTC, NickLambellGCH commented on lib/table/coursecompletiontablemerger.php
> +                $completion->timecompleted > $existingCompletion->timecompleted)) {
This `if` will need some reformatting too. The condition group should be expanded out fully as well. e.g.
```php
if (
    !empty($completion->timecompleted) &&
    (
        empty($existingCompletion->timecompleted) ||
        $completion->timecompleted > $existingCompletion->timecompleted
    )
) {
```

2025-04-11 02:55 UTC, NickLambellGCH commented on lang/en/tool_mergeusers.php
>  $string['coursecompletionaction_desc'] = 'Description of the course completion action.';
These strings should be removed since the setting was removed

2025-04-14 00:46 UTC, merged